blake_harris_law:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: blake-harris-law
      dataset: dev 
      threads: 4  
      OPTIONAL_CONFIG: VALUE

    prod:
      type: bigquery
      method: oauth
      project: blake-harris-law
      dataset: prod 
      threads: 4  
      OPTIONAL_CONFIG: VALUE

  target: dev