select
    id as account_id,
    owner_id,
    owner_name,
    owner_email,
    last_activity_time,
    exchange_rate,
    currency,
    created_time,
    modified_time,
    created_by_id,
    created_by_name,
    created_by_email,
    modified_by_id,
    modified_by_name,
    modified_by_email,
    review_process_delegate,
    review_process_approve,
    review_process_reject,
    review_process_resubmit,
    approval_delegate,
    approval_approve,
    approval_reject,
    approval_resubmit,
    account_name,
    phone,
    website,
    account_type,
    industry,
    annual_revenue,
    sic_code,
    account_site,
    billing_country,
    billing_street,
    billing_code,
    shipping_city,
    shipping_country,
    shipping_code,
    billing_city,
    shipping_street,
    ownership,
    description,
    rating,
    shipping_state,
    employees,
    account_number,
    ticker_symbol,
    billing_state,
    fax,
    _fivetran_deleted,
    approved,
    approval_state,
    currency_symbol,
    in_merge,
    process_flow,
    editable,
    orchestration,
    custom_tag,
    custom_locked_s as custom_locked_status,
    custom_locked_for_me,
    custom_is_duplicate,
    custom_zia_owner_assignment,
    custom_record_image,
    custom_layout_id,
    custom_state,
    custom_first_utm_medium as first_utm_medium,
    custom_first_utm_content as first_utm_content,
    custom_last_utm_medium as last_utm_medium,
    custom_first_utm_campaign as first_utm_campaign,
    custom_first_touch_url as first_touch_url,
    custom_first_utm_term as first_utm_term,
    custom_gclid_value as gclid_value,
    custom_last_utm_campaign as last_utm_campaign,
    custom_last_touch_url as last_touch_url,
    custom_last_utm_content as last_utm_content,
    custom_last_utm_term as last_utm_term,
    custom_first_utm_source as first_utm_source,
    custom_entry_date as entry_date,
    custom_last_utm_source as last_utm_source

from {{ source("zoho", "account") }}
