select
    id as contact_id,
    owner_id,
    owner_name,
    owner_email,
    last_activity_time,
    exchange_rate,
    currency,
    created_time,
    modified_time,
    created_by_id,
    created_by_name,
    created_by_email,
    modified_by_id,
    modified_by_name,
    modified_by_email,
    review_process_delegate,
    review_process_approve,
    review_process_reject,
    review_process_resubmit,
    approval_delegate,
    approval_approve,
    approval_reject,
    approval_resubmit,
    email,
    first_name,
    last_name,
    full_name,
    phone,
    mobile,
    fax,
    other_phone,
    mailing_state,
    other_state,
    other_country,
    department,
    assistant,
    mailing_country,
    other_city,
    negative_touch_point_score,
    positive_touch_point_score,
    last_contacted_on,
    home_phone,
    score,
    negative_score,
    secondary_email,
    touch_point_score,
    positive_score,
    description,
    mailing_zip,
    number_of_chats,
    twitter,
    other_zip,
    mailing_street,
    salutation,
    asst_phone,
    skype_id,
    email_opt_out,
    date_of_birth,
    title,
    other_street,
    _fivetran_deleted,
    approved,
    approval_state,
    currency_symbol,
    in_merge,
    process_flow,
    editable,
    orchestration,
    _fivetran_synced,
    custom_mailing_city as mailing_city,
    custom_cost_per_click as cost_per_click,
    custom_cost_per_conversion as cost_per_conversion,
    custom_state as state,
    custom_tag as tag,
    custom_locked_s as locked_s,
    custom_lead_source as lead_source,
    custom_locked_for_me as locked_for_me,
    custom_is_duplicate as is_duplicate,
    custom_account_name as account_name,
    custom_zia_owner_assignment as zia_owner_assignment,
    custom_record_image as record_image,
    custom_layout_id as layout_id,
    custom_referring_url as referring_url,
    custom_conversion_export_status as conversion_export_status,
    custom_gclid as gclid,
    custom_tracking_source as tracking_source,
    custom_contact_email as contact_email,
    custom_contact_state as contact_state,
    custom_contact_city as contact_city,
    custom_postal_zip_code as postal_zip_code,
    custom_ctm_first_name as ctm_first_name,
    custom_ctm_last_name as ctm_last_name,
    custom_conversion_exported_on as conversion_exported_on,
    custom_ad_network as ad_network,
    custom_ad_campaign_name as ad_campaign_name,
    custom_click_type as click_type,
    custom_device_type as device_type,
    custom_ad_click_date as ad_click_date,
    custom_keyword as keyword,
    custom_ad_group_name as ad_group_name,
    custom_ad as ad,
    custom_reason_for_conversion_failure as reason_for_conversion_failure
from {{ source("zoho", "contact") }}
