SELECT
    id as lead_id,
    converted_detail_deal as deal_id,
    owner_id,
    owner_name,
    owner_email,
    last_activity_time,
    exchange_rate,
    currency,
    date(created_time) as created_date,
    date(modified_time) as modified_date,
    created_by_id,
    created_by_name,
    created_by_email,
    modified_by_id,
    modified_by_name,
    modified_by_email,
    review_process_delegate,
    review_process_approve,
    review_process_reject,
    review_process_resubmit,
    approval_delegate,
    approval_approve,
    approval_reject,
    approval_resubmit,
    company,
    email,
    first_name,
    last_name,
    full_name,
    salutation,
    lead_source,
    lead_status,
    phone,
    street,
    zip_code,
    no_of_employees,
    state,
    industry,
    industry_type,
    country,
    fax,
    first_visited_time,
    mobile,
    designation,
    email_opt_out,
    skype_id,
    twitter,
    website,
    touch_point_score,
    positive_score,
    converted_detail_deal,
    converted_detail_convert_date,
    converted_detail_contact,
    converted_detail_converted_by,
    converted_detail_account,
    _fivetran_deleted,
    approved,
    approval_state,
    currency_symbol,
    in_merge,
    process_flow,
    editable,
    orchestration,
    converted,
    _fivetran_synced,
    custom_tag AS tag,
    custom_locked_s AS locked_s,
    custom_annual_revenue AS annual_revenue,
    custom_locked_for_me AS locked_for_me,
    custom_zia_owner_assignment AS zia_owner_assignment,
    custom_cost_per_click AS cost_per_click,
    custom_cost_per_conversion AS cost_per_conversion,
    custom_layout_id AS layout_id,
    custom_first_utm_medium AS first_utm_medium,
    custom_first_utm_content AS first_utm_content,
    custom_last_utm_medium AS last_utm_medium,
    custom_first_utm_campaign AS first_utm_campaign,
    custom_first_touch_url AS first_touch_url,
    custom_first_utm_term AS first_utm_term,
    custom_gclid_value AS gclid_value,
    custom_last_utm_campaign AS last_utm_campaign,
    custom_last_touch_url AS last_touch_url,
    custom_last_utm_content AS last_utm_content,
    custom_last_utm_term AS last_utm_term,
    custom_first_utm_source AS first_utm_source,
    CAST(REGEXP_EXTRACT(custom_entry_date, r'^\d{4}-\d{2}-\d{2}') AS DATE) AS entry_date,
    custom_last_utm_source AS last_utm_source,
    custom_referring_url AS referring_url,
    custom_conversion_export_status AS conversion_export_status,
    custom_lead_type AS lead_type,
    custom_lead_channel AS lead_channel,
    custom_gclid AS gclid,
    custom_description AS description,
    custom_over_1_m AS over_1_m,
    custom_tracking_source AS tracking_source,
    custom_contact_email AS contact_email,
    custom_contact_state AS contact_state,
    custom_contact_city AS contact_city,
    custom_postal_zip_code AS postal_zip_code,
    custom_ctm_first_name AS ctm_first_name,
    custom_fbclid AS fbclid,
    custom_ctm_last_name AS ctm_last_name,
    custom_secondary_email AS secondary_email,
    custom_ad_click_date AS ad_click_date,
    custom_conversion_exported_on AS conversion_exported_on,
    custom_ad_network AS ad_network,
    custom_ad_campaign_name AS ad_campaign_name,
    custom_click_type AS click_type,
    custom_device_type AS device_type,
    custom_ad_group_name AS ad_group_name,
    custom_ad AS ad,
    custom_keyword AS keyword,
    custom_category AS category

FROM {{ source("zoho", "lead") }}