with
    deals as (
        select
            deal_id,
            deal_name,
            account_name,
            account_id,
            contact_name,
            contact_id,
            type as deal_type,
            description as deal_description,
            date(closing_date) as deal_closing_date,
            created_date,
            amount,
            owner_id,
            owner_name,
            owner_email,
            last_activity_time,
            exchange_rate,
            currency,
            review_process_delegate,
            review_process_approve,
            review_process_reject,
            review_process_resubmit,
            approval_delegate,
            approval_approve,
            approval_reject,
            approval_resubmit,
            campaign_source_name,
            expected_revenue,
            approved,
            in_merge,
            editable,
            orchestration,
            followed,
            last_utm_medium,
            tag,
            first_touch_url,
            first_utm_campaign,
            first_utm_term,
            utm_source,
            first_utm_medium,
            first_utm_content,
            lead_source,
            last_utm_term,
            last_utm_campaign,
            last_touch_url,
            last_utm_content,
            last_utm_source,
            lead_type,
            lead_channel,
            gclid_value,
            gclid,
            referring_url,
            tracking_source,
            fbclid,
            channel_source,
            ad_click_date,
            ad_group_name,
            ad,
            ad_network,
            ad_campaign_name,
            keyword,
            platform,
            channel

        from {{ ref('stg_zh_deals') }}
    ),

    stage_history as (
        select deal_id, amount, stage_change_date, close_date, stage_name

        from {{ ref('stg_zh_deal_stage_history') }}
    )

select
    de.deal_id,
    deal_name,
    account_name,
    account_id,
    contact_name,
    contact_id,
    deal_type,
    deal_description,
    coalesce(date(de.deal_closing_date), date(sg.close_date)) as deal_closing_date,
    created_date,
    stage_change_date,
    sg.stage_name,
    coalesce(de.amount, sg.amount) as amount,
    owner_id,
    owner_name,
    owner_email,
    last_activity_time,
    exchange_rate,
    currency,
    review_process_delegate,
    review_process_approve,
    review_process_reject,
    review_process_resubmit,
    approval_delegate,
    approval_approve,
    approval_reject,
    approval_resubmit,
    campaign_source_name,
    expected_revenue,
    approved,
    in_merge,
    editable,
    orchestration,
    followed,
    last_utm_medium,
    tag,
    first_touch_url,
    first_utm_campaign,
    first_utm_term,
    utm_source,
    first_utm_medium,
    first_utm_content,
    lead_source,
    last_utm_term,
    last_utm_campaign,
    last_touch_url,
    last_utm_content,
    last_utm_source,
    lead_type,
    lead_channel,
    gclid_value,
    gclid,
    referring_url,
    tracking_source,
    fbclid,
    channel_source,
    ad_click_date,
    ad_group_name,
    ad,
    ad_network,
    ad_campaign_name,
    keyword,
    platform,
    channel

from deals as de
left join stage_history as sg on de.deal_id = sg.deal_id
