-- 14-Day Waiting Period
SELECT
    deal_id,
    created_date,
    stage_change_date,
    stage_name,
    first_touch_url,
    COALESCE(ad_campaign_name, first_utm_campaign) AS utm_campaign,
    COALESCE(keyword, first_utm_term) AS utm_term,
    utm_source,
    first_utm_medium AS utm_medium,
    first_utm_content AS utm_content,
    lead_source,
    platform,
    channel,
    COALESCE(gclid_value, gclid) AS gclid_value,
    fbclid,
    0 AS closed_won_amount,
    0 AS opportunity_amount,
    1 AS is_14_day_waiting_period,
    0 AS is_24_hour_waiting_period,
    0 AS is_30_day_waiting_period_1,
    0 AS is_30_day_waiting_period_2,
    0 AS is_48_hour_waiting_period,
    0 AS is_60_day_follow_up,
    0 AS is_7_day_waiting_period,
    0 AS is_agreement_pending,
    0 AS is_closed_lost,
    0 AS is_closed_lost_to_competition,
    0 AS is_closed_won,
    0 AS is_consult_scheduled,
    0 AS is_contacted,
    0 AS is_contract_out,
    0 AS is_follow_up_required,
    0 AS is_id_decision_makers,
    0 AS is_needs_analysis,
    0 AS is_negotiation_review,
    0 AS is_new_lead,
    0 AS is_proposal_price_quote,
    0 AS is_qualification,
    0 AS is_qualified_lead,
    0 AS is_value_proposition
FROM {{ ref('stg_zh_deals') }}
WHERE stage_name = '14-Day Waiting Period'

UNION ALL

-- 24-Hour Waiting Period
SELECT
    deal_id,
    created_date,
    stage_change_date,
    stage_name,
    first_touch_url,
    COALESCE(ad_campaign_name, first_utm_campaign) AS utm_campaign,
    COALESCE(keyword, first_utm_term) AS utm_term,
    utm_source,
    first_utm_medium AS utm_medium,
    first_utm_content AS utm_content,
    lead_source,
    platform,
    channel,
    COALESCE(gclid_value, gclid) AS gclid_value,
    fbclid,
    0 AS closed_won_amount,
    0 AS opportunity_amount,
    0 AS is_14_day_waiting_period,
    1 AS is_24_hour_waiting_period,
    0 AS is_30_day_waiting_period_1,
    0 AS is_30_day_waiting_period_2,
    0 AS is_48_hour_waiting_period,
    0 AS is_60_day_follow_up,
    0 AS is_7_day_waiting_period,
    0 AS is_agreement_pending,
    0 AS is_closed_lost,
    0 AS is_closed_lost_to_competition,
    0 AS is_closed_won,
    0 AS is_consult_scheduled,
    0 AS is_contacted,
    0 AS is_contract_out,
    0 AS is_follow_up_required,
    0 AS is_id_decision_makers,
    0 AS is_needs_analysis,
    0 AS is_negotiation_review,
    0 AS is_new_lead,
    0 AS is_proposal_price_quote,
    0 AS is_qualification,
    0 AS is_qualified_lead,
    0 AS is_value_proposition
FROM {{ ref('stg_zh_deals') }}
WHERE stage_name = '24-Hour Waiting Period'

UNION ALL

-- 30-Day Waiting Period 1
SELECT
    deal_id,
    created_date,
    stage_change_date,
    stage_name,
    first_touch_url,
    COALESCE(ad_campaign_name, first_utm_campaign) AS utm_campaign,
    COALESCE(keyword, first_utm_term) AS utm_term,
    utm_source,
    first_utm_medium AS utm_medium,
    first_utm_content AS utm_content,
    lead_source,
    platform,
    channel,
    COALESCE(gclid_value, gclid) AS gclid_value,
    fbclid,
    0 AS closed_won_amount,
    0 AS opportunity_amount,
    0 AS is_14_day_waiting_period,
    0 AS is_24_hour_waiting_period,
    1 AS is_30_day_waiting_period_1,
    0 AS is_30_day_waiting_period_2,
    0 AS is_48_hour_waiting_period,
    0 AS is_60_day_follow_up,
    0 AS is_7_day_waiting_period,
    0 AS is_agreement_pending,
    0 AS is_closed_lost,
    0 AS is_closed_lost_to_competition,
    0 AS is_closed_won,
    0 AS is_consult_scheduled,
    0 AS is_contacted,
    0 AS is_contract_out,
    0 AS is_follow_up_required,
    0 AS is_id_decision_makers,
    0 AS is_needs_analysis,
    0 AS is_negotiation_review,
    0 AS is_new_lead,
    0 AS is_proposal_price_quote,
    0 AS is_qualification,
    0 AS is_qualified_lead,
    0 AS is_value_proposition
FROM {{ ref('stg_zh_deals') }}
WHERE stage_name = '30-Day Waiting Period 1'

UNION ALL

-- 30-Day Waiting Period 2
SELECT
    deal_id,
    created_date,
    stage_change_date,
    stage_name,
    first_touch_url,
    COALESCE(ad_campaign_name, first_utm_campaign) AS utm_campaign,
    COALESCE(keyword, first_utm_term) AS utm_term,
    utm_source,
    first_utm_medium AS utm_medium,
    first_utm_content AS utm_content,
    lead_source,
    platform,
    channel,
    COALESCE(gclid_value, gclid) AS gclid_value,
    fbclid,
    0 AS closed_won_amount,
    0 AS opportunity_amount,
    0 AS is_14_day_waiting_period,
    0 AS is_24_hour_waiting_period,
    0 AS is_30_day_waiting_period_1,
    1 AS is_30_day_waiting_period_2,
    0 AS is_48_hour_waiting_period,
    0 AS is_60_day_follow_up,
    0 AS is_7_day_waiting_period,
    0 AS is_agreement_pending,
    0 AS is_closed_lost,
    0 AS is_closed_lost_to_competition,
    0 AS is_closed_won,
    0 AS is_consult_scheduled,
    0 AS is_contacted,
    0 AS is_contract_out,
    0 AS is_follow_up_required,
    0 AS is_id_decision_makers,
    0 AS is_needs_analysis,
    0 AS is_negotiation_review,
    0 AS is_new_lead,
    0 AS is_proposal_price_quote,
    0 AS is_qualification,
    0 AS is_qualified_led,
    0 AS is_value_proposition
FROM {{ ref('stg_zh_deals') }}
WHERE stage_name = '30-Day Waiting Period 2'

UNION ALL

-- 48-Hour Waiting Period
SELECT
    deal_id,
    created_date,
    stage_change_date,
    stage_name,
    first_touch_url,
    COALESCE(ad_campaign_name, first_utm_campaign) AS utm_campaign,
    COALESCE(keyword, first_utm_term) AS utm_term,
    utm_source,
    first_utm_medium AS utm_medium,
    first_utm_content AS utm_content,
    lead_source,
    platform,
    channel,
    COALESCE(gclid_value, gclid) AS gclid_value,
    fbclid,
    0 AS closed_won_amount,
    0 AS opportunity_amount,
    0 AS is_14_day_waiting_period,
    0 AS is_24_hour_waiting_period,
    0 AS is_30_day_waiting_period_1,
    0 AS is_30_day_waiting_period_2,
    1 AS is_48_hour_waiting_period,
    0 AS is_60_day_follow_up,
    0 AS is_7_day_waiting_period,
    0 AS is_agreement_pending,
    0 AS is_closed_lost,
    0 AS is_closed_lost_to_competition,
    0 AS is_closed_won,
    0 AS is_consult_scheduled,
    0 AS is_contacted,
    0 AS is_contract_out,
    0 AS is_follow_up_required,
    0 AS is_id_decision_makers,
    0 AS is_needs_analysis,
    0 AS is_negotiation_review,
    0 AS is_new_lead,
    0 AS is_proposal_price_quote,
    0 AS is_qualification,
    0 AS is_qualified_lead,
    0 AS is_value_proposition
FROM {{ ref('stg_zh_deals') }}
WHERE stage_name = '48-Hour Waiting Period'

UNION ALL

-- 60 Day Follow-Up
SELECT
    deal_id,
    created_date,
    stage_change_date,
    stage_name,
    first_touch_url,
    COALESCE(ad_campaign_name, first_utm_campaign) AS utm_campaign,
    COALESCE(keyword, first_utm_term) AS utm_term,
    utm_source,
    first_utm_medium AS utm_medium,
    first_utm_content AS utm_content,
    lead_source,
    platform,
    channel,
    COALESCE(gclid_value, gclid) AS gclid_value,
    fbclid,
    0 AS closed_won_amount,
    0 AS opportunity_amount,
    0 AS is_14_day_waiting_period,
    0 AS is_24_hour_waiting_period,
    0 AS is_30_day_waiting_period_1,
    0 AS is_30_day_waiting_period_2,
    0 AS is_48_hour_waiting_period,
    1 AS is_60_day_follow_up,
    0 AS is_7_day_waiting_period,
    0 AS is_agreement_pending,
    0 AS is_closed_lost,
    0 AS is_closed_lost_to_competition,
    0 AS is_closed_won,
    0 AS is_consult_scheduled,
    0 AS is_contacted,
    0 AS is_contract_out,
    0 AS is_follow_up_required,
    0 AS is_id_decision_makers,
    0 AS is_needs_analysis,
    0 AS is_negotiation_review,
    0 AS is_new_lead,
    0 AS is_proposal_price_quote,
    0 AS is_qualification,
    0 AS is_qualified_lead,
    0 AS is_value_proposition
FROM {{ ref('stg_zh_deals') }}
WHERE stage_name = '60 Day Follow-Up'

UNION ALL

-- 7-Day Waiting Period
SELECT
    deal_id,
    created_date,
    stage_change_date,
    stage_name,
    first_touch_url,
    COALESCE(ad_campaign_name, first_utm_campaign) AS utm_campaign,
    COALESCE(keyword, first_utm_term) AS utm_term,
    utm_source,
    first_utm_medium AS utm_medium,
    first_utm_content AS utm_content,
    lead_source,
    platform,
    channel,
    COALESCE(gclid_value, gclid) AS gclid_value,
    fbclid,
    0 AS closed_won_amount,
    0 AS opportunity_amount,
    0 AS is_14_day_waiting_period,
    0 AS is_24_hour_waiting_period,
    0 AS is_30_day_waiting_period_1,
    0 AS is_30_day_waiting_period_2,
    0 AS is_48_hour_waiting_period,
    0 AS is_60_day_follow_up,
    1 AS is_7_day_waiting_period,
    0 AS is_agreement_pending,
    0 AS is_closed_lost,
    0 AS is_closed_lost_to_competition,
    0 AS is_closed_won,
    0 AS is_consult_scheduled,
    0 AS is_contacted,
    0 AS is_contract_out,
    0 AS is_follow_up_required,
    0 AS is_id_decision_makers,
    0 AS is_needs_analysis,
    0 AS is_negotiation_review,
    0 AS is_new_lead,
    0 AS is_proposal_price_quote,
    0 AS is_qualification,
    0 AS is_qualified_lead,
    0 AS is_value_proposition
FROM {{ ref('stg_zh_deals') }}
WHERE stage_name = '7-Day Waiting Period'

UNION ALL

-- Agreement Pending
SELECT
    deal_id,
    created_date,
    stage_change_date,
    stage_name,
    first_touch_url,
    COALESCE(ad_campaign_name, first_utm_campaign) AS utm_campaign,
    COALESCE(keyword, first_utm_term) AS utm_term,
    utm_source,
    first_utm_medium AS utm_medium,
    first_utm_content AS utm_content,
    lead_source,
    platform,
    channel,
    COALESCE(gclid_value, gclid) AS gclid_value,
    fbclid,
    0 AS closed_won_amount,
    0 AS opportunity_amount,
    0 AS is_14_day_waiting_period,
    0 AS is_24_hour_waiting_period,
    0 AS is_30_day_waiting_period_1,
    0 AS is_30_day_waiting_period_2,
    0 AS is_48_hour_waiting_period,
    0 AS is_60_day_follow_up,
    0 AS is_7_day_waiting_period,
    1 AS is_agreement_pending,
    0 AS is_closed_lost,
    0 AS is_closed_lost_to_competition,
    0 AS is_closed_won,
    0 AS is_consult_scheduled,
    0 AS is_contacted,
    0 AS is_contract_out,
    0 AS is_follow_up_required,
    0 AS is_id_decision_makers,
    0 AS is_needs_analysis,
    0 AS is_negotiation_review,
    0 AS is_new_lead,
    0 AS is_proposal_price_quote,
    0 AS is_qualification,
    0 AS is_qualified_lead,
    0 AS is_value_proposition
FROM {{ ref('stg_zh_deals') }}
WHERE stage_name = 'Agreement Pending'

UNION ALL

-- Closed Lost
SELECT
    deal_id,
    created_date,
    stage_change_date,
    stage_name,
    first_touch_url,
    COALESCE(ad_campaign_name, first_utm_campaign) AS utm_campaign,
    COALESCE(keyword, first_utm_term) AS utm_term,
    utm_source,
    first_utm_medium AS utm_medium,
    first_utm_content AS utm_content,
    lead_source,
    platform,
    channel,
    COALESCE(gclid_value, gclid) AS gclid_value,
    fbclid,
    0 AS closed_won_amount,
    0 AS opportunity_amount,
    0 AS is_14_day_waiting_period,
    0 AS is_24_hour_waiting_period,
    0 AS is_30_day_waiting_period_1,
    0 AS is_30_day_waiting_period_2,
    0 AS is_48_hour_waiting_period,
    0 AS is_60_day_follow_up,
    0 AS is_7_day_waiting_period,
    0 AS is_agreement_pending,
    1 AS is_closed_lost,
    0 AS is_closed_lost_to_competition,
    0 AS is_closed_won,
    0 AS is_consult_scheduled,
    0 AS is_contacted,
    0 AS is_contract_out,
    0 AS is_follow_up_required,
    0 AS is_id_decision_makers,
    0 AS is_needs_analysis,
    0 AS is_negotiation_review,
    0 AS is_new_lead,
    0 AS is_proposal_price_quote,
    0 AS is_qualification,
    0 AS is_qualified_lead,
    0 AS is_value_proposition
FROM {{ ref('stg_zh_deals') }}
WHERE stage_name = 'Closed Lost'

UNION ALL

-- Closed Lost to Competition
SELECT
    deal_id,
    created_date,
    stage_change_date,
    stage_name,
    first_touch_url,
    COALESCE(ad_campaign_name, first_utm_campaign) AS utm_campaign,
    COALESCE(keyword, first_utm_term) AS utm_term,
    utm_source,
    first_utm_medium AS utm_medium,
    first_utm_content AS utm_content,
    lead_source,
    platform,
    channel,
    COALESCE(gclid_value, gclid) AS gclid_value,
    fbclid,
    0 AS closed_won_amount,
    0 AS opportunity_amount,
    0 AS is_14_day_waiting_period,
    0 AS is_24_hour_waiting_period,
    0 AS is_30_day_waiting_period_1,
    0 AS is_30_day_waiting_period_2,
    0 AS is_48_hour_waiting_period,
    0 AS is_60_day_follow_up,
    0 AS is_7_day_waiting_period,
    0 AS is_agreement_pending,
    0 AS is_closed_lost,
    1 AS is_closed_lost_to_competition,
    0 AS is_closed_won,
    0 AS is_consult_scheduled,
    0 AS is_contacted,
    0 AS is_contract_out,
    0 AS is_follow_up_required,
    0 AS is_id_decision_makers,
    0 AS is_needs_analysis,
    0 AS is_negotiation_review,
    0 AS is_new_lead,
    0 AS is_proposal_price_quote,
    0 AS is_qualification,
    0 AS is_qualified_lead,
    0 AS is_value_proposition
FROM {{ ref('stg_zh_deals') }}
WHERE stage_name = 'Closed Lost to Competition'

UNION ALL

-- Closed Won
SELECT
    deal_id,
    created_date,
    stage_change_date,
    stage_name,
    first_touch_url,
    COALESCE(ad_campaign_name, first_utm_campaign) AS utm_campaign,
    COALESCE(keyword, first_utm_term) AS utm_term,
    utm_source,
    first_utm_medium AS utm_medium,
    first_utm_content AS utm_content,
    lead_source,
    platform,
    channel,
    COALESCE(gclid_value, gclid) AS gclid_value,
    fbclid,
    coalesce(amount, 0) AS closed_won_amount,
    0 AS opportunity_amount,
    0 AS is_14_day_waiting_period,
    0 AS is_24_hour_waiting_period,
    0 AS is_30_day_waiting_period_1,
    0 AS is_30_day_waiting_period_2,
    0 AS is_48_hour_waiting_period,
    0 AS is_60_day_follow_up,
    0 AS is_7_day_waiting_period,
    0 AS is_agreement_pending,
    0 AS is_closed_lost,
    0 AS is_closed_lost_to_competition,
    1 AS is_closed_won,
    0 AS is_consult_scheduled,
    0 AS is_contacted,
    0 AS is_contract_out,
    0 AS is_follow_up_required,
    0 AS is_id_decision_makers,
    0 AS is_needs_analysis,
    0 AS is_negotiation_review,
    0 AS is_new_lead,
    0 AS is_proposal_price_quote,
    0 AS is_qualification,
    0 AS is_qualified_lead,
    0 AS is_value_proposition
FROM {{ ref('stg_zh_deals') }}
WHERE stage_name = 'Closed Won'

UNION ALL

-- Consult Scheduled
SELECT
    deal_id,
    created_date,
    stage_change_date,
    stage_name,
    first_touch_url,
    COALESCE(ad_campaign_name, first_utm_campaign) AS utm_campaign,
    COALESCE(keyword, first_utm_term) AS utm_term,
    utm_source,
    first_utm_medium AS utm_medium,
    first_utm_content AS utm_content,
    lead_source,
    platform,
    channel,
    COALESCE(gclid_value, gclid) AS gclid_value,
    fbclid,
    0 AS closed_won_amount,
    0 AS opportunity_amount,
    0 AS is_14_day_waiting_period,
    0 AS is_24_hour_waiting_period,
    0 AS is_30_day_waiting_period_1,
    0 AS is_30_day_waiting_period_2,
    0 AS is_48_hour_waiting_period,
    0 AS is_60_day_follow_up,
    0 AS is_7_day_waiting_period,
    0 AS is_agreement_pending,
    0 AS is_closed_lost,
    0 AS is_closed_lost_to_competition,
    0 AS is_closed_won,
    1 AS is_consult_scheduled,
    0 AS is_contacted,
    0 AS is_contract_out,
    0 AS is_follow_up_required,
    0 AS is_id_decision_makers,
    0 AS is_needs_analysis,
    0 AS is_negotiation_review,
    0 AS is_new_lead,
    0 AS is_proposal_price_quote,
    0 AS is_qualification,
    0 AS is_qualified_lead,
    0 AS is_value_proposition
FROM {{ ref('stg_zh_deals') }}
WHERE stage_name = 'Consult Scheduled'

UNION ALL

-- Contacted
SELECT
    deal_id,
    created_date,
    stage_change_date,
    stage_name,
    first_touch_url,
    COALESCE(ad_campaign_name, first_utm_campaign) AS utm_campaign,
    COALESCE(keyword, first_utm_term) AS utm_term,
    utm_source,
    first_utm_medium AS utm_medium,
    first_utm_content AS utm_content,
    lead_source,
    platform,
    channel,
    COALESCE(gclid_value, gclid) AS gclid_value,
    fbclid,
    0 AS closed_won_amount,
    0 AS opportunity_amount,
    0 AS is_14_day_waiting_period,
    0 AS is_24_hour_waiting_period,
    0 AS is_30_day_waiting_period_1,
    0 AS is_30_day_waiting_period_2,
    0 AS is_48_hour_waiting_period,
    0 AS is_60_day_follow_up,
    0 AS is_7_day_waiting_period,
    0 AS is_agreement_pending,
    0 AS is_closed_lost,
    0 AS is_closed_lost_to_competition,
    0 AS is_closed_won,
    0 AS is_consult_scheduled,
    1 AS is_contacted,
    0 AS is_contract_out,
    0 AS is_follow_up_required,
    0 AS is_id_decision_makers,
    0 AS is_needs_analysis,
    0 AS is_negotiation_review,
    0 AS is_new_lead,
    0 AS is_proposal_price_quote,
    0 AS is_qualification,
    0 AS is_qualified_lead,
    0 AS is_value_proposition
FROM {{ ref('stg_zh_deals') }}
WHERE stage_name = 'Contacted'

UNION ALL

-- Contract Out
SELECT
    deal_id,
    created_date,
    stage_change_date,
    stage_name,
    first_touch_url,
    COALESCE(ad_campaign_name, first_utm_campaign) AS utm_campaign,
    COALESCE(keyword, first_utm_term) AS utm_term,
    utm_source,
    first_utm_medium AS utm_medium,
    first_utm_content AS utm_content,
    lead_source,
    platform,
    channel,
    COALESCE(gclid_value, gclid) AS gclid_value,
    fbclid,
    0 AS closed_won_amount,
    0 AS opportunity_amount,
    0 AS is_14_day_waiting_period,
    0 AS is_24_hour_waiting_period,
    0 AS is_30_day_waiting_period_1,
    0 AS is_30_day_waiting_period_2,
    0 AS is_48_hour_waiting_period,
    0 AS is_60_day_follow_up,
    0 AS is_7_day_waiting_period,
    0 AS is_agreement_pending,
    0 AS is_closed_lost,
    0 AS is_closed_lost_to_competition,
    0 AS is_closed_won,
    0 AS is_consult_scheduled,
    0 AS is_contacted,
    1 AS is_contract_out,
    0 AS is_follow_up_required,
    0 AS is_id_decision_makers,
    0 AS is_needs_analysis,
    0 AS is_negotiation_review,
    0 AS is_new_lead,
    0 AS is_proposal_price_quote,
    0 AS is_qualification,
    0 AS is_qualified_lead,
    0 AS is_value_proposition
FROM {{ ref('stg_zh_deals') }}
WHERE stage_name = 'Contract Out'

UNION ALL

-- Follow-Up Required
SELECT
    deal_id,
    created_date,
    stage_change_date,
    stage_name,
    first_touch_url,
    COALESCE(ad_campaign_name, first_utm_campaign) AS utm_campaign,
    COALESCE(keyword, first_utm_term) AS utm_term,
    utm_source,
    first_utm_medium AS utm_medium,
    first_utm_content AS utm_content,
    lead_source,
    platform,
    channel,
    COALESCE(gclid_value, gclid) AS gclid_value,
    fbclid,
    0 AS closed_won_amount,
    0 AS opportunity_amount,
    0 AS is_14_day_waiting_period,
    0 AS is_24_hour_waiting_period,
    0 AS is_30_day_waiting_period_1,
    0 AS is_30_day_waiting_period_2,
    0 AS is_48_hour_waiting_period,
    0 AS is_60_day_follow_up,
    0 AS is_7_day_waiting_period,
    0 AS is_agreement_pending,
    0 AS is_closed_lost,
    0 AS is_closed_lost_to_competition,
    0 AS is_closed_won,
    0 AS is_consult_scheduled,
    0 AS is_contacted,
    0 AS is_contract_out,
    1 AS is_follow_up_required,
    0 AS is_id_decision_makers,
    0 AS is_needs_analysis,
    0 AS is_negotiation_review,
    0 AS is_new_lead,
    0 AS is_proposal_price_quote,
    0 AS is_qualification,
    0 AS is_qualified_lead,
    0 AS is_value_proposition
FROM {{ ref('stg_zh_deals') }}
WHERE stage_name = 'Follow-Up Required'

UNION ALL

-- Id. Decision Makers
SELECT
    deal_id,
    created_date,
    stage_change_date,
    stage_name,
    first_touch_url,
    COALESCE(ad_campaign_name, first_utm_campaign) AS utm_campaign,
    COALESCE(keyword, first_utm_term) AS utm_term,
    utm_source,
    first_utm_medium AS utm_medium,
    first_utm_content AS utm_content,
    lead_source,
    platform,
    channel,
    COALESCE(gclid_value, gclid) AS gclid_value,
    fbclid,
    0 AS closed_won_amount,
    0 AS opportunity_amount,
    0 AS is_14_day_waiting_period,
    0 AS is_24_hour_waiting_period,
    0 AS is_30_day_waiting_period_1,
    0 AS is_30_day_waiting_period_2,
    0 AS is_48_hour_waiting_period,
    0 AS is_60_day_follow_up,
    0 AS is_7_day_waiting_period,
    0 AS is_agreement_pending,
    0 AS is_closed_lost,
    0 AS is_closed_lost_to_competition,
    0 AS is_closed_won,
    0 AS is_consult_scheduled,
    0 AS is_contacted,
    0 AS is_contract_out,
    0 AS is_follow_up_required,
    1 AS is_id_decision_makers,
    0 AS is_needs_analysis,
    0 AS is_negotiation_review,
    0 AS is_new_lead,
    0 AS is_proposal_price_quote,
    0 AS is_qualification,
    0 AS is_qualified_lead,
    0 AS is_value_proposition
FROM {{ ref('stg_zh_deals') }}
WHERE stage_name = 'Id. Decision Makers'

UNION ALL

-- Needs Analysis
SELECT
    deal_id,
    created_date,
    stage_change_date,
    stage_name,
    first_touch_url,
    COALESCE(ad_campaign_name, first_utm_campaign) AS utm_campaign,
    COALESCE(keyword, first_utm_term) AS utm_term,
    utm_source,
    first_utm_medium AS utm_medium,
    first_utm_content AS utm_content,
    lead_source,
    platform,
    channel,
    COALESCE(gclid_value, gclid) AS gclid_value,
    fbclid,
    0 AS closed_won_amount,
    0 AS opportunity_amount,
    0 AS is_14_day_waiting_period,
    0 AS is_24_hour_waiting_period,
    0 AS is_30_day_waiting_period_1,
    0 AS is_30_day_waiting_period_2,
    0 AS is_48_hour_waiting_period,
    0 AS is_60_day_follow_up,
    0 AS is_7_day_waiting_period,
    0 AS is_agreement_pending,
    0 AS is_closed_lost,
    0 AS is_closed_lost_to_competition,
    0 AS is_closed_won,
    0 AS is_consult_scheduled,
    0 AS is_contacted,
    0 AS is_contract_out,
    0 AS is_follow_up_required,
    0 AS is_id_decision_makers,
    1 AS is_needs_analysis,
    0 AS is_negotiation_review,
    0 AS is_new_lead,
    0 AS is_proposal_price_quote,
    0 AS is_qualification,
    0 AS is_qualified_lead,
    0 AS is_value_proposition
FROM {{ ref('stg_zh_deals') }}
WHERE stage_name = 'Needs Analysis'

UNION ALL

-- Negotiation/Review
SELECT
    deal_id,
    created_date,
    stage_change_date,
    stage_name,
    first_touch_url,
    COALESCE(ad_campaign_name, first_utm_campaign) AS utm_campaign,
    COALESCE(keyword, first_utm_term) AS utm_term,
    utm_source,
    first_utm_medium AS utm_medium,
    first_utm_content AS utm_content,
    lead_source,
    platform,
    channel,
    COALESCE(gclid_value, gclid) AS gclid_value,
    fbclid,
    0 AS closed_won_amount,
    0 AS opportunity_amount,
    0 AS is_14_day_waiting_period,
    0 AS is_24_hour_waiting_period,
    0 AS is_30_day_waiting_period_1,
    0 AS is_30_day_waiting_period_2,
    0 AS is_48_hour_waiting_period,
    0 AS is_60_day_follow_up,
    0 AS is_7_day_waiting_period,
    0 AS is_agreement_pending,
    0 AS is_closed_lost,
    0 AS is_closed_lost_to_competition,
    0 AS is_closed_won,
    0 AS is_consult_scheduled,
    0 AS is_contacted,
    0 AS is_contract_out,
    0 AS is_follow_up_required,
    0 AS is_id_decision_makers,
    0 AS is_needs_analysis,
    1 AS is_negotiation_review,
    0 AS is_new_lead,
    0 AS is_proposal_price_quote,
    0 AS is_qualification,
    0 AS is_qualified_lead,
    0 AS is_value_proposition
FROM {{ ref('stg_zh_deals') }}
WHERE stage_name = 'Negotiation/Review'

UNION ALL

-- New Lead
SELECT
    deal_id,
    created_date,
    stage_change_date,
    stage_name,
    first_touch_url,
    COALESCE(ad_campaign_name, first_utm_campaign) AS utm_campaign,
    COALESCE(keyword, first_utm_term) AS utm_term,
    utm_source,
    first_utm_medium AS utm_medium,
    first_utm_content AS utm_content,
    lead_source,
    platform,
    channel,
    COALESCE(gclid_value, gclid) AS gclid_value,
    fbclid,
    0 AS closed_won_amount,
    0 AS opportunity_amount,
    0 AS is_14_day_waiting_period,
    0 AS is_24_hour_waiting_period,
    0 AS is_30_day_waiting_period_1,
    0 AS is_30_day_waiting_period_2,
    0 AS is_48_hour_waiting_period,
    0 AS is_60_day_follow_up,
    0 AS is_7_day_waiting_period,
    0 AS is_agreement_pending,
    0 AS is_closed_lost,
    0 AS is_closed_lost_to_competition,
    0 AS is_closed_won,
    0 AS is_consult_scheduled,
    0 AS is_contacted,
    0 AS is_contract_out,
    0 AS is_follow_up_required,
    0 AS is_id_decision_makers,
    0 AS is_needs_analysis,
    0 AS is_negotiation_review,
    1 AS is_new_lead,
    0 AS is_proposal_price_quote,
    0 AS is_qualification,
    0 AS is_qualified_lead,
    0 AS is_value_proposition
FROM {{ ref('stg_zh_deals') }}
WHERE stage_name = 'New Lead'

UNION ALL

-- Proposal/Price Quote
SELECT
    deal_id,
    created_date,
    stage_change_date,
    stage_name,
    first_touch_url,
    COALESCE(ad_campaign_name, first_utm_campaign) AS utm_campaign,
    COALESCE(keyword, first_utm_term) AS utm_term,
    utm_source,
    first_utm_medium AS utm_medium,
    first_utm_content AS utm_content,
    lead_source,
    platform,
    channel,
    COALESCE(gclid_value, gclid) AS gclid_value,
    fbclid,
    0 AS closed_won_amount,
    0 AS opportunity_amount,
    0 AS is_14_day_waiting_period,
    0 AS is_24_hour_waiting_period,
    0 AS is_30_day_waiting_period_1,
    0 AS is_30_day_waiting_period_2,
    0 AS is_48_hour_waiting_period,
    0 AS is_60_day_follow_up,
    0 AS is_7_day_waiting_period,
    0 AS is_agreement_pending,
    0 AS is_closed_lost,
    0 AS is_closed_lost_to_competition,
    0 AS is_closed_won,
    0 AS is_consult_scheduled,
    0 AS is_contacted,
    0 AS is_contract_out,
    0 AS is_follow_up_required,
    0 AS is_id_decision_makers,
    0 AS is_needs_analysis,
    0 AS is_negotiation_review,
    0 AS is_new_lead,
    1 AS is_proposal_price_quote,
    0 AS is_qualification,
    0 AS is_qualified_lead,
    0 AS is_value_proposition
FROM {{ ref('stg_zh_deals') }}
WHERE stage_name = 'Proposal/Price Quote'

UNION ALL

-- Qualification
SELECT
    deal_id,
    created_date,
    stage_change_date,
    stage_name,
    first_touch_url,
    COALESCE(ad_campaign_name, first_utm_campaign) AS utm_campaign,
    COALESCE(keyword, first_utm_term) AS utm_term,
    utm_source,
    first_utm_medium AS utm_medium,
    first_utm_content AS utm_content,
    lead_source,
    platform,
    channel,
    COALESCE(gclid_value, gclid) AS gclid_value,
    fbclid,
    0 AS closed_won_amount,
    0 AS opportunity_amount,
    0 AS is_14_day_waiting_period,
    0 AS is_24_hour_waiting_period,
    0 AS is_30_day_waiting_period_1,
    0 AS is_30_day_waiting_period_2,
    0 AS is_48_hour_waiting_period,
    0 AS is_60_day_follow_up,
    0 AS is_7_day_waiting_period,
    0 AS is_agreement_pending,
    0 AS is_closed_lost,
    0 AS is_closed_lost_to_competition,
    0 AS is_closed_won,
    0 AS is_consult_scheduled,
    0 AS is_contacted,
    0 AS is_contract_out,
    0 AS is_follow_up_required,
    0 AS is_id_decision_makers,
    0 AS is_needs_analysis,
    0 AS is_negotiation_review,
    0 AS is_new_lead,
    0 AS is_proposal_price_quote,
    1 AS is_qualification,
    0 AS is_qualified_lead,
    0 AS is_value_proposition
FROM {{ ref('stg_zh_deals') }}
WHERE stage_name = 'Qualification'

UNION ALL

-- Qualified Lead
SELECT
    deal_id,
    created_date,
    stage_change_date,
    stage_name,
    first_touch_url,
    COALESCE(ad_campaign_name, first_utm_campaign) AS utm_campaign,
    COALESCE(keyword, first_utm_term) AS utm_term,
    utm_source,
    first_utm_medium AS utm_medium,
    first_utm_content AS utm_content,
    lead_source,
    platform,
    channel,
    COALESCE(gclid_value, gclid) AS gclid_value,
    fbclid,
    0 AS closed_won_amount,
    amount AS opportunity_amount,
    0 AS is_14_day_waiting_period,
    0 AS is_24_hour_waiting_period,
    0 AS is_30_day_waiting_period_1,
    0 AS is_30_day_waiting_period_2,
    0 AS is_48_hour_waiting_period,
    0 AS is_60_day_follow_up,
    0 AS is_7_day_waiting_period,
    0 AS is_agreement_pending,
    0 AS is_closed_lost,
    0 AS is_closed_lost_to_competition,
    0 AS is_closed_won,
    0 AS is_consult_scheduled,
    0 AS is_contacted,
    0 AS is_contract_out,
    0 AS is_follow_up_required,
    0 AS is_id_decision_makers,
    0 AS is_needs_analysis,
    0 AS is_negotiation_review,
    0 AS is_new_lead,
    0 AS is_proposal_price_quote,
    0 AS is_qualification,
    1 AS is_qualified_lead,
    0 AS is_value_proposition
FROM {{ ref('stg_zh_deals') }}
WHERE stage_name = 'Qualified Lead'

UNION ALL

-- Value Proposition
SELECT
    deal_id,
    created_date,
    stage_change_date,
    stage_name,
    first_touch_url,
    COALESCE(ad_campaign_name, first_utm_campaign) AS utm_campaign,
    COALESCE(keyword, first_utm_term) AS utm_term,
    utm_source,
    first_utm_medium AS utm_medium,
    first_utm_content AS utm_content,
    lead_source,
    platform,
    channel,
    COALESCE(gclid_value, gclid) AS gclid_value,
    fbclid,
    0 AS closed_won_amount,
    0 AS opportunity_amount,
    0 AS is_14_day_waiting_period,
    0 AS is_24_hour_waiting_period,
    0 AS is_30_day_waiting_period_1,
    0 AS is_30_day_waiting_period_2,
    0 AS is_48_hour_waiting_period,
    0 AS is_60_day_follow_up,
    0 AS is_7_day_waiting_period,
    0 AS is_agreement_pending,
    0 AS is_closed_lost,
    0 AS is_closed_lost_to_competition,
    0 AS is_closed_won,
    0 AS is_consult_scheduled,
    0 AS is_contacted,
    0 AS is_contract_out,
    0 AS is_follow_up_required,
    0 AS is_id_decision_makers,
    0 AS is_needs_analysis,
    0 AS is_negotiation_review,
    0 AS is_new_lead,
    0 AS is_proposal_price_quote,
    0 AS is_qualification,
    0 AS is_qualified_lead,
    1 AS is_value_proposition
FROM {{ ref('stg_zh_deals') }}
WHERE stage_name = 'Value Proposition'