select
    deal_id,
    created_date,
    stage_change_date,
    stage_name,
    first_touch_url,
    utm_campaign,
    utm_term,
    utm_source,
    utm_medium,
    utm_content,
    lead_source,
    platform,
    channel,
    gclid_value,
    fbclid,
    closed_won_amount,
    opportunity_amount,
    is_14_day_waiting_period,
    is_24_hour_waiting_period,
    is_30_day_waiting_period_1,
    is_30_day_waiting_period_2,
    is_48_hour_waiting_period,
    is_60_day_follow_up,
    is_60_day_waiting_period,
    is_7_day_waiting_period,
    is_agreement_pending,
    is_closed_lost,
    is_closed_lost_to_competition,
    is_closed_won,
    is_consult_scheduled,
    is_contacted,
    is_contract_out,
    is_follow_up_required,
    is_id_decision_makers,
    is_needs_analysis,
    is_negotiation_review,
    is_new_lead,
    is_proposal_price_quote,
    is_qualification,
    is_qualified_lead,
    is_value_proposition,
    0 as is_contacted_scheduled,
    0 as is_junk_leads,
    1 as is_deal,
    0 as is_lead,
    0 as total_leads,
    0 as active_leads

from {{ ref("fct_zh_deals_unfreeze") }}

union all 

select
    lead_id as deal_id,
    entry_date as created_date,
    modified_date as stage_change_date,
    lead_status as stage_name,
    first_touch_url,
    utm_campaign,
    utm_term,
    utm_source,
    utm_medium,
    utm_content,
    lead_source,
    platform,
    channel,
    gclid_value,
    fbclid,
    0 closed_won_amount,
    0 as opportunity_amount,
    0 as is_14_day_waiting_period,
    0 as is_24_hour_waiting_period,
    0 as is_30_day_waiting_period_1,
    0 as is_30_day_waiting_period_2,
    0 as is_48_hour_waiting_period,
    0 as is_60_day_follow_up,
    0 as is_60_day_waiting_period,
    0 as is_7_day_waiting_period,
    0 as is_agreement_pending,
    0 as is_closed_lost,
    0 as is_closed_lost_to_competition,
    0 as is_closed_won,
    0 as is_consult_scheduled,
    0 as is_contacted,
    0 as is_contract_out,
    0 as is_follow_up_required,
    0 as is_id_decision_makers,
    0 as is_needs_analysis,
    0 as is_negotiation_review,
    0 as is_new_lead,
    0 as is_proposal_price_quote,
    0 as is_qualification,
    0 as is_qualified_lead,
    0 as is_value_proposition,
    is_contacted_scheduled,
    is_junk_leads,
    0 as is_deal,
    1 as is_lead,
    total_leads,
    active_leads

from {{ ref("fct_zh_leads") }}