version: 2

sources:
  - name: google_ads  # Logical name for the source
    database: 	blake-harris-law  # BigQuery project ID
    schema: google_ads  # BigQuery dataset
    tables:
      - name: account_performance_report # name you want to call it
        identifier: account_performance_report # name for the source table
        description: "Contains data about Google ads source synced from Airbyte."
      - name: campaign # name you want to call it
        identifier: campaign # name for the source table
        description: "Contains data about Google ads source synced from Airbyte."
